### ISSUE TITLE
Keep this up to date?

### ISSUE THREAD

**Issue by itshaydendev** [unix/koa-ts#19]
## Type
- [ ] Bug
- [ ] Feature
- [x] Help   

## Description

Any intentions on keeping this up to date? As a big Koa user, I'd love to lend a hand where I can :)

**Comment by unix** [comment]
It's seems to work well at the moment, I don't want to make this repo very complicated, so all the time no new features have been added. But there are still some issues to think about:

  - All dependencies need to be updated, but this requires regression testing.
  - The stack of repo `type-orm` is too large, i didn't find a good substitute.

Do you have any ideas or want to add ? And do you have any recommendation about `orm` on `TypeScript`?

**Comment by itshaydendev** [comment]
TypeORM is great, I see no reason to remove it. It's what basically every TS project uses, so I don't recommend straying.

Other than that, I was more offering to help maintain and keep this up to date. Maybe add GitHub Actions support to keep deps up to date for you

**Comment by unix** [comment]
Here is a stack trace after using the `type-orm` (the performance impact of such a large stack):
![type-orm](https://user-images.githubusercontent.com/11304944/77232965-4522a980-6bdf-11ea-8dbd-def16f5265a2.png)


This is because `type-orm` didn't separate every `db-driver` very well in design, even if you only use one type of `database`, all `db-drivers` are loaded into memory. (this becomes a `bottleneck` when performance is "sensitive")

Thanks so much for your help, you can create PR at any time. In addition, i'm not good at English, the `readme.md` document may have some flaws, can you reivew these documents?

**Comment by itshaydendev** [comment]
Sure can! I'll look over it all for you! 👍
